### ISSUE TITLE
跑不起来

### ISSUE THREAD

**Issue by whereiscode** [GitLqr/UniappIseXfyun#1]
vite v2.9.15 building for development...
[plugin:uni:mp-using-component] Cannot read property 'local' of undefined
at pages/index/index.vue:1:0

**Comment by whereiscode** [comment]
还有请问  这个测试必须真机吗？

**Comment by GitLqr** [comment]
1、按 readme 配置后，是可以运行的。
2、因为用到录音功能，最好是真机测试；直接在 微信开发者工具 上录音的话，可能录不到声音。
