### ISSUE TITLE
运行时'uni' 不是内部或外部命令，也不是可运行的程序

### ISSUE THREAD

**Issue by zhengzhiwu2009** [GitLqr/UniappIseXfyun#2]
D:\git_workspace\github\UniappIseXfyun>npm run dev:mp-weixin

> uni-preset-vue@0.0.0 dev:mp-weixin D:\git_workspace\github\UniappIseXfyun
> uni -p mp-weixin

'uni' 不是内部或外部命令，也不是可运行的程序
或批处理文件。
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! uni-preset-vue@0.0.0 dev:mp-weixin: `uni -p mp-weixin`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the uni-preset-vue@0.0.0 dev:mp-weixin script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
npm WARN Local package.json exists, but node_modules missing, did you mean to install?

**Comment by GitLqr** [comment]
先执行 npm install ，确保所有库都正常安装了，注意安装过程看控制台有没有报错
