### ISSUE TITLE
operateRecorder:fail Failed to execute 'stop' on 'MediaRecorder': The MediaRecorder's state is 'inactive'.

### ISSUE THREAD

**Issue by zhengzhiwu2009** [GitLqr/UniappIseXfyun#3]
![image](https://user-images.githubusercontent.com/35989383/231633500-37d672e5-2cdf-4db0-ac1d-892f74f27ab5.png)

大佬你好，我这边在微信开发工具成功允许，但出现点击开始录音按钮后，立刻变为从暂停录音到开始录音

**Comment by GitLqr** [comment]
用真机测试看，之前遇到过授权失败的话，工程会触发录音stop操作，但此时录音还没开始，从而导致报错（之前即使录音还没开始，触发 stop 也不会报错的，现在小程序底层逻辑改了），你跟着这思路完善下代码吧（在stop处判断录音是否已经开始）
